# Generated by Django 4.0.3 on 2022-03-30 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_packages_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='seats',
            new_name='seat',
        ),
    ]
