# Generated by Django 4.0.3 on 2022-03-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_seats_packages_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
