# Generated by Django 4.0.3 on 2022-04-01 13:23

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_packages_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='upload',
            field=models.FileField(null=True, upload_to=base.models.upload_to),
        ),
    ]
