# Generated by Django 4.0.3 on 2022-04-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_packages_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='upload',
            new_name='files',
        ),
    ]
