# Generated by Django 4.0.3 on 2022-04-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_packages_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%M/%D'),
        ),
    ]
