# Generated by Django 4.0.3 on 2022-04-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_packages_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='files',
        ),
    ]
