# Generated by Django 4.0.3 on 2022-05-01 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_packages_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='seat',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='PackageDaysDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_count', models.IntegerField(null=True)),
                ('day_description', models.CharField(max_length=2000, null=True)),
                ('package_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.packages')),
            ],
        ),
    ]
