# Generated by Django 4.0.3 on 2022-05-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_packages_days_alter_packages_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
